FROM rust:1.80-alpine@sha256:596c7fa13f7458097b8c88ad83f33420da0341e2f5b544e34d9aa18a22fe11d0 AS build
RUN apk update && apk add protoc protobuf-dev build-base && rm -rf /var/cache/apk/*
ENV TARGET_LIBC=musl TARGET_VENDOR=unknown

WORKDIR /usr/src/app
COPY . .
RUN ./hack/initrd/build.sh && cp target/initrd/initrd-* target/initrd/initrd

FROM scratch AS final
COPY --from=build /usr/src/app/target/initrd/initrd /krata/initrd
