FROM rust:1.79-alpine AS build
RUN apk update && apk add protoc protobuf-dev build-base && rm -rf /var/cache/apk/*
ENV TARGET_LIBC=musl TARGET_VENDOR=unknown

WORKDIR /usr/src/app
COPY . .
RUN ./hack/build/cargo.sh build --release --bin kratad
RUN mv ./target/$(./hack/build/target.sh)/release/kratad /usr/sbin

FROM scratch
ENTRYPOINT ["/usr/sbin/kratad"]
COPY --from=build /usr/sbin/kratad /usr/sbin/kratad
COPY ./resources/systemd/kratad.service /usr/lib/systemd/system/kratad.service
