FROM rust:1.81-alpine@sha256:e4ab5bdd6d6c93e984ba5d320691d7f4bddb1e061102a1def6ec203de8547472 AS build
RUN apk update && apk add protoc protobuf-dev build-base && rm -rf /var/cache/apk/*
ENV TARGET_LIBC=musl TARGET_VENDOR=unknown

WORKDIR /usr/src/app
COPY . .
RUN ./hack/initrd/build.sh && cp target/initrd/initrd-* target/initrd/initrd

FROM scratch AS final
COPY --from=build /usr/src/app/target/initrd/initrd /krata/initrd
