FROM rust:1.79-alpine@sha256:a454f49f2e15e233f829a0fd9a7cbdac64b6f38ec08aeac227595d4fc6eb6d4d AS build
RUN apk update && apk add protoc protobuf-dev build-base && rm -rf /var/cache/apk/*
ENV TARGET_LIBC=musl TARGET_VENDOR=unknown

WORKDIR /usr/src/app
COPY . .
RUN ./hack/build/cargo.sh build --release --bin kratactl
RUN mv ./target/$(./hack/build/target.sh)/release/kratactl /usr/sbin

FROM scratch
ENTRYPOINT ["/usr/sbin/kratactl"]
COPY --from=build /usr/sbin/kratactl /usr/sbin/kratactl
