FROM rust:1.80-alpine@sha256:596c7fa13f7458097b8c88ad83f33420da0341e2f5b544e34d9aa18a22fe11d0 AS build
RUN apk update && apk add protoc protobuf-dev build-base && rm -rf /var/cache/apk/*
ENV TARGET_LIBC=musl TARGET_VENDOR=unknown

WORKDIR /usr/src/app
COPY . .
RUN ./hack/build/cargo.sh build --release --bin kratanet
RUN mv ./target/$(./hack/build/target.sh)/release/kratanet /usr/sbin

FROM scratch
ENTRYPOINT ["/usr/sbin/kratanet"]
COPY --from=build /usr/sbin/kratanet /usr/sbin/kratanet
COPY ./resources/systemd/kratanet.service /usr/lib/systemd/system/kratanet.service
